### ISSUE TITLE
Shift in dem.value_at_coord or dem.show

### ISSUE THREAD

**Issue by LucBeraud** [GlacioHack/geoutils#355] opened 2023-03-02 14:18 UTC
**Describe the bug**
There seems to be a diagonal ~ half-pixel shift between the _DEM.show()_ displays and the _DEM.value_at_coord()_ output.

**To Reproduce**
`import xdem`
`img = xdem.DEM(gu.examples.get_path('everest_landsat_b4'))`
`target_x, target_y = 486811, 3097050 # example of coordinate`
`fig,ax=plt.subplots(1,1)`
`img.show(vmin=50, vmax=200, ax=ax)`
`ax.set_xlim(target_x-60,target_x+60); ax.set_ylim(target_y-60,target_y+60) # zoom on the area`
`ax.scatter(target_x, target_y,c='r') # plot the desired coordinate on the image plot`
`ax.set_title('at ({}, {}), dem.value_at_coords={}'.format(target_x, target_y, np.round(img.value_at_coords(target_x, target_y), 2))) # prints as figure title the value returned by value_at_coords()`
`ax.plot([486805, 486805, 486805+30, 486805+30, 486805],[3097056,3097056-30, 3097056-30, 3097056, 3097056]) # if coord falls in this blue polygon`
`ax.plot([486820, 486820, 486820+30, 486820+30, 486820],[3097040,3097040-30, 3097040-30, 3097040, 3097040]) # it returns the value of this orange one`

**Expected behavior**
The _value_at_coord()_ value does not return same value as the plot most of the time, I expect that the _value_at_coords()_ (169 in the example, value of the orange box pixel) matches the _show()_ pixels (131 in the example, under the red point).

**System (please complete the following information):**
 - OS: Ubuntu 22
 - Environment : xdem (0.0.7, 823fff239daa864748677e4d6bcb6bd153c15969 commit), geoutils (0.0.10)
![Capture d’écran du 2023-03-02 15-15-19](https://user-images.githubusercontent.com/38109225/222454028-c2c14822-2a7c-45a7-9d4e-4d29561559d5.png)

**Comment by rhugonnet** [comment] 2023-03-02 22:38
Thanks for the reproducible example, helped a lot!

Found the guilty line: https://github.com/GlacioHack/geoutils/pull/351/commits/326772649c5d6a6c9a3c0bb7e61c1acd4a8bcb60

Turns out our `test_value_at_coords` function had the same value for neighbouring pixels, and so it went unnoticed. This is fixed as well: https://github.com/GlacioHack/geoutils/pull/351/commits/147363ebe9c3ce53b55a7a7f9407f3219387295a

Will be closed when #351 is merged.

**Closed** 2023-04-15 00:24 UTC
Labels: bug
